### PR TITLE
Add foreword mapping the translators and the stories they worked on

### PR DESCRIPTION
**Pull request by robinwhittleton**
I’d been a little confused as to why the halftitle I’d copied in from the Ivan Bunin collection existed, but when I investigated further I wound the foreword I’d forgot I’d written. This commit replicates that for this collection, and describes the English translators and the stories they worked on.

Now there’s a foreword, the halftitle needs to come back in.

### CODE REVIEW

**Comment by acabal** [comment]
Great, thanks! Two notes: 1. Short stories get quotes and not italics; 2. can you add a footer with your name, year, and (optionally) your location? I think those are nice details to have for these kinds of editorial notes.

**Comment by robinwhittleton** [comment]
Sounds good, I’ll make those changes to Bunin as well.

One follow up question: these are a mix of shorts and novellas. Deitalicise the novellas too?

**Comment by acabal** [comment]
Novellas keep italics. I'll add that to the list in the manual. Thanks!

**Comment by acabal** [comment]
Actually, I take that back--let's quote novellas, since we would include them in a Short Fiction collection. Sorry!

**Comment by robinwhittleton** [comment]
Done. Does this look like the correct format?

**Comment by acabal** [comment]
Excellent, thanks!

**Pull request merged**
